// providers-gen.ts — generates app/providers.tsx from the i18n config.
//
// The provider is a GENERATED file (like app/page.tsx server wrappers): its
// messages imports must match the configured locales (the old static template
// hardcoded en/fr/es — an added Italian locale silently never loaded its
// dictionary on the live site), and since the locale-routes feature the
// active locale is ROUTE-FIRST: a `/fr/...` URL wins over the stored client
// preference, so `/fr` server-renders French HTML (the SEO path). The
// `locale-change` event + localStorage remain the client channel used by the
// canvas preview and by unprefixed URLs.
//
// Regenerated by ensureIntlScaffold whenever the expected source drifts
// (locale added/removed). Hand-written providers (no generation markers) are
// left alone.

import type { I18nConfig } from '@/shared/types';

/** Version marker — bump when the template shape changes so older generated
 *  providers are upgraded on load. */
export const PROVIDERS_MARKER = '@revyme-providers v3';

/** A locale code safe to interpolate into generated code/identifiers. */
function safeLocale(code: string): boolean {
  return /^[a-z]{2,3}(-[A-Za-z0-9]+)?$/.test(code);
}

function importIdent(code: string): string {
  return code.replace(/-/g, '_') + 'Messages';
}

export function buildProvidersSource(config: I18nConfig): string {
  const locales = config.locales.map((l) => l.code).filter(safeLocale);
  const codes = locales.length > 0 ? locales : ['en'];
  const defaultLocale = safeLocale(config.defaultLocale) ? config.defaultLocale : 'en';
  const imports = codes
    .map((c) => `import ${importIdent(c)} from '@/messages/${c}.json';`)
    .join('\n');
  const mapEntries = codes.map((c) => `  '${c}': ${importIdent(c)},`).join('\n');

  return `'use client';

/** ${PROVIDERS_MARKER} — GENERATED from i18n/config.json (locales: ${codes.join(', ')}).
 *  The editor regenerates this file when locales change. Do not hand-edit. */

import { useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { ThemeProvider } from 'next-themes';
import { NextIntlClientProvider } from 'next-intl';

${imports}

const messagesByLocale: Record<string, any> = {
${mapEntries}
};
const DEFAULT_LOCALE = '${defaultLocale}';
const LOCALES = Object.keys(messagesByLocale);

// ── Link attributes runtime (data-smooth-scroll / data-keep-params) ──────────
// The attributes are the source of truth for the Link tool's Smooth Scroll and
// Keep Params toggles. A per-link inline onClick used to be their ONLY
// implementation, and any path that dropped it (paste, AI edit) left the panel
// saying "Smooth: Yes" while the live site jumped. This document-level
// listener honours the attributes on every link, handler or not. It runs in
// the bubble phase AFTER React's own handlers, so a link that still carries
// the inline handler (which calls preventDefault) is left alone — no double
// navigation. Modified clicks, other buttons, new-tab links and cross-origin
// links are never touched.
const SMOOTH_KEY = 'revyme:smooth-target';
function revymeNavClick(e, nav) {
  if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
  const a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
  if (!a || a.target === '_blank' || a.hasAttribute('download')) return;
  let url;
  try { url = new URL(a.getAttribute('href') || '', window.location.href); } catch { return; }
  if (url.origin !== window.location.origin) return;
  const smooth = a.dataset.smoothScroll === 'true';
  const keep = a.dataset.keepParams === 'true';
  if (smooth && url.hash) {
    const id = decodeURIComponent(url.hash.slice(1));
    if (url.pathname === window.location.pathname) {
      const el = id ? document.getElementById(id) : null;
      if (el) {
        e.preventDefault();
        el.scrollIntoView({ behavior: 'smooth' });
        try { window.history.pushState(null, '', url.pathname + url.search + url.hash); } catch {}
        return;
      }
    } else if (id) {
      // Cross-page: let the router navigate, scroll on arrival (see effect below).
      try { window.sessionStorage.setItem(SMOOTH_KEY, id); } catch {}
    }
  }
  if (keep && window.location.search) {
    const merged = new URL(url.href);
    new URLSearchParams(window.location.search).forEach((v, k) => { if (!merged.searchParams.has(k)) merged.searchParams.set(k, v); });
    if (merged.href !== url.href) {
      e.preventDefault();
      nav.push(merged.pathname + merged.search + merged.hash);
    }
  }
}
/** Scroll smoothly to the section a cross-page smooth link targeted, once
 *  the destination page has mounted it (polls up to 10s — SPA routers do no
 *  native hash scrolling). */
function revymeScrollOnArrival() {
  let id = null;
  try { id = window.sessionStorage.getItem(SMOOTH_KEY); } catch {}
  if (!id) return () => {};
  try { window.sessionStorage.removeItem(SMOOTH_KEY); } catch {}
  let n = 0;
  const t = window.setInterval(() => {
    const el = document.getElementById(id);
    if (el) { window.clearInterval(t); el.scrollIntoView({ behavior: 'smooth' }); }
    else if (++n > 100) window.clearInterval(t);
  }, 100);
  return () => window.clearInterval(t);
}

/** '/fr/about' -> 'fr' when fr is a configured non-default locale, else null. */
function localeFromPath(pathname: string | null): string | null {
  const seg = (pathname || '/').split('/')[1];
  return seg && seg !== DEFAULT_LOCALE && LOCALES.includes(seg) ? seg : null;
}

export function Providers({ children }: { children: React.ReactNode }) {
  // ROUTE-FIRST locale: /fr/... serves French on the server render itself
  // (usePathname resolves during SSR), so crawlers get translated HTML.
  const pathname = usePathname();
  const router = useRouter();
  const routeLocale = localeFromPath(pathname);
  const [clientLocale, setClientLocale] = useState(DEFAULT_LOCALE);
  const locale = routeLocale ?? clientLocale;

  // Link attributes runtime — see revymeNavClick above.
  useEffect(() => {
    const onClick = (e: MouseEvent) => revymeNavClick(e, router);
    document.addEventListener('click', onClick);
    return () => document.removeEventListener('click', onClick);
  }, [router]);
  useEffect(() => revymeScrollOnArrival(), [pathname]);

  // Client channel: persisted preference + the 'locale-change' event any
  // component (LocaleSwitcher) can dispatch. Only applies on unprefixed URLs.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const stored = window.localStorage.getItem('locale');
      if (stored && messagesByLocale[stored]) setClientLocale(stored);
    } catch { /* private mode — ignore */ }

    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      const next = detail?.locale;
      if (typeof next === 'string' && messagesByLocale[next]) setClientLocale(next);
    };
    window.addEventListener('locale-change', handler);
    return () => window.removeEventListener('locale-change', handler);
  }, []);

  // Mirror the ACTIVE locale to <html lang> (+ dir for RTL scripts) and
  // persist it, so :lang() CSS fires and the choice survives navigation to
  // unprefixed URLs.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      if (document.documentElement.lang !== locale) document.documentElement.lang = locale;
      const rtl = ['ar', 'he', 'fa', 'ur', 'ps', 'sd', 'ku', 'dv', 'yi'].includes(locale.split('-')[0]);
      if (rtl) document.documentElement.dir = 'rtl';
      else document.documentElement.removeAttribute('dir');
    }
    try { window.localStorage.setItem('locale', locale); } catch { /* ignore */ }
  }, [locale]);

  const messages = messagesByLocale[locale] || messagesByLocale[DEFAULT_LOCALE];

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
        {/* lang on a wrapper (display:contents = no box) so :lang() styles
            match in the SERVER-rendered HTML too — <html lang> is only
            patched client-side. */}
        <div lang={locale} style={{ display: 'contents' }}>
          {children}
        </div>
      </ThemeProvider>
    </NextIntlClientProvider>
  );
}
`;
}

/** Does this providers.tsx look editor-GENERATED (any version)? Generated
 *  files are safe to regenerate; a hand-written provider is left alone. */
export function looksGeneratedProviders(code: string): boolean {
  return code.includes(PROVIDERS_MARKER)
    || (code.includes('messagesByLocale') && code.includes("'locale-change'"));
}
