/**
 * smooth-scroll-config.ts — data model + parse/serialize for Smooth Scroll
 * (Lenis), the page-level scroll effect configured from the viewport's
 * Animation section beside Page Transition.
 *
 * The whole config lives in a generated module `app/smooth-scroll.ts`:
 *   export const SMOOTH_SCROLL = { __default?, pages: { '/route': {…} } } as const;
 * Every page carries its own setting in `pages[route]` (Home = '/'); there is
 * no site-wide scope in the panel (user decision 2026-09-16: "we just apply
 * it page per page"). `__default` is still READ, so a module written before
 * that decision keeps working, but nothing writes it. The generated
 * controller (smooth-scroll-gen.ts) resolves the active route and runs Lenis.
 */

import { trace } from '@/shared/debug-trace';

export type SmoothScrollOrientation = 'vertical' | 'horizontal';

export interface SmoothScrollConfig {
  /** false = native scrolling on this page. */
  enabled: boolean;
  /** "Intensity": Lenis `duration` × 10 (12 = Lenis's own 1.2s default). */
  intensity: number;
  /** Smooth the mouse wheel (Lenis `smoothWheel`). */
  smoothWheel: boolean;
  /** Smooth touch scrolling too (Lenis `syncTouch`). Off by default, as in Lenis. */
  smoothTouch: boolean;
  orientation: SmoothScrollOrientation;
  /** Loop the page end back to the top (Lenis `infinite`). */
  infinite: boolean;
}

export interface SmoothScrollMap {
  __default?: SmoothScrollConfig;
  pages: Record<string, SmoothScrollConfig>;
}

export function createDefaultSmoothScroll(): SmoothScrollConfig {
  return { enabled: true, intensity: 12, smoothWheel: true, smoothTouch: false, orientation: 'vertical', infinite: false };
}

const SMOOTH_SCROLL_CONST = 'SMOOTH_SCROLL';

/** A route is the home page (stored under '/'). */
function isHome(route: string): boolean {
  return route === '/' || route === '' || route === 'home';
}

/** Coerce anything read back from the module into a complete config. */
export function normalizeSmoothScroll(raw: Partial<SmoothScrollConfig> | undefined | null): SmoothScrollConfig {
  const d = createDefaultSmoothScroll();
  if (!raw || typeof raw !== 'object') return d;
  const num = Number(raw.intensity);
  return {
    enabled: raw.enabled !== false,
    intensity: Number.isFinite(num) ? Math.min(100, Math.max(1, num)) : d.intensity,
    smoothWheel: raw.smoothWheel !== false,
    smoothTouch: raw.smoothTouch === true,
    orientation: raw.orientation === 'horizontal' ? 'horizontal' : 'vertical',
    infinite: raw.infinite === true,
  };
}

/** Parse the `export const SMOOTH_SCROLL = {…} as const;` object (pure JSON body). */
export function parseSmoothScroll(code: string | null | undefined): SmoothScrollMap {
  if (!code) return { pages: {} };
  const at = code.indexOf(`${SMOOTH_SCROLL_CONST} =`);
  if (at === -1) return { pages: {} };
  const start = code.indexOf('{', at);
  const end = code.lastIndexOf('}');
  if (start === -1 || end <= start) return { pages: {} };
  try {
    const obj = JSON.parse(code.slice(start, end + 1)) as SmoothScrollMap;
    const pages: Record<string, SmoothScrollConfig> = {};
    for (const [route, cfg] of Object.entries(obj?.pages ?? {})) pages[route] = normalizeSmoothScroll(cfg);
    const out: SmoothScrollMap = { pages };
    if (obj?.__default) out.__default = normalizeSmoothScroll(obj.__default);
    return out;
  } catch {
    trace.error('smooth-scroll-config:parse', 'failed to JSON.parse SMOOTH_SCROLL');
    return { pages: {} };
  }
}

export function serializeSmoothScroll(map: SmoothScrollMap): string {
  const normalized: SmoothScrollMap = { pages: map.pages ?? {} };
  if (map.__default) normalized.__default = map.__default;
  return `// @generated by Revyme — Smooth Scroll. Edit via the viewport's Animation panel.\n`
    + `export const ${SMOOTH_SCROLL_CONST} = ${JSON.stringify(normalized, null, 2)} as const;\n`;
}

const keyOf = (route: string) => (isHome(route) ? '/' : route);

/** Set the config of one page (pure). */
export function setSmoothScrollInMap(map: SmoothScrollMap, route: string, cfg: SmoothScrollConfig): SmoothScrollMap {
  return setSmoothScrollForRoutesInMap(map, [route], cfg);
}

/** Set the same config on several pages at once (pure) — one write for an import. */
export function setSmoothScrollForRoutesInMap(map: SmoothScrollMap, routes: string[], cfg: SmoothScrollConfig): SmoothScrollMap {
  const next: SmoothScrollMap = { ...map, pages: { ...(map.pages ?? {}) } };
  for (const r of routes) next.pages[keyOf(r)] = { ...cfg };
  return next;
}

/** Remove one page's config (pure). Home also clears a legacy site default. */
export function removeSmoothScrollFromMap(map: SmoothScrollMap, route: string): SmoothScrollMap {
  const next: SmoothScrollMap = { ...map, pages: { ...(map.pages ?? {}) } };
  delete next.pages[keyOf(route)];
  if (isHome(route)) delete next.__default;
  return next;
}

/** The config of this page (what the panel row edits). Home also reads a legacy site default. */
export function ownSmoothScroll(map: SmoothScrollMap, route: string): SmoothScrollConfig | null {
  return map.pages?.[keyOf(route)] ?? (isHome(route) ? map.__default ?? null : null);
}

/** `/journal/[slug]` matches `/journal/anything`; a catch-all matches the rest. */
export function routeMatches(route: string, pathname: string): boolean {
  const rs = route.split('/').filter(Boolean);
  const ps = pathname.split('/').filter(Boolean);
  for (let i = 0; i < rs.length; i++) {
    if (/^\[\.\.\..+\]$/.test(rs[i])) return true;
    if (i >= ps.length) return false;
    if (/^\[.+\]$/.test(rs[i])) continue;
    if (rs[i] !== ps[i]) return false;
  }
  return rs.length === ps.length;
}

/** The config in effect on `pathname`: an exact page, a dynamic-route page, then the site default. */
export function resolveSmoothScroll(map: SmoothScrollMap, pathname: string): SmoothScrollConfig | null {
  const p = pathname || '/';
  if (map.pages?.[p]) return map.pages[p];
  for (const [route, cfg] of Object.entries(map.pages ?? {})) if (routeMatches(route, p)) return cfg;
  return map.__default ?? null;
}
