/**
 * smooth-scroll-gen.ts — the Smooth Scroll (Lenis) RUNTIME in user source.
 *
 * Two generated files at the app root, beside the root layout:
 *   - app/smooth-scroll.ts            → the SMOOTH_SCROLL data map (editor writes it)
 *   - app/smooth-scroll-controller.tsx → <SmoothScroll />, a client controller
 * and `<SmoothScroll />` is mounted once inside `<body>` of `app/layout.tsx`.
 *
 * Why the ROOT layout and not the LayoutClient page transitions use: every
 * project has a root layout, template or not (an imported site without a
 * an imported layout has no route group), and the editor preview renders the same
 * layout chain a published site does. The controller renders nothing.
 *
 * The controller carries its own route resolver (a hand-mirrored copy of
 * resolveSmoothScroll) so the deployed file has no editor imports.
 */

import { trace } from '@/shared/debug-trace';
import { projectFS } from '../project/project-fs';
import { serializeSmoothScroll } from '../project/smooth-scroll-config';

import { SMOOTH_SCROLL_DATA_PATH, SMOOTH_SCROLL_CONTROLLER_PATH } from './smooth-scroll-layout';
export { SMOOTH_SCROLL_DATA_PATH, SMOOTH_SCROLL_CONTROLLER_PATH };

/** Bump when the controller's logic changes: an outdated copy is rewritten on the next edit. */
export const SMOOTH_SCROLL_MARKER = '@smooth-scroll v1';

export const SMOOTH_SCROLL_CONTROLLER_SOURCE = `'use client';
// @generated by Revyme — Smooth Scroll controller. Do not edit. ${SMOOTH_SCROLL_MARKER}
import * as React from 'react';
import { usePathname } from 'next/navigation';
import Lenis from 'lenis';
import { SMOOTH_SCROLL } from './smooth-scroll';

// Lenis's own stylesheet (lenis/dist/lenis.css), inlined so the controller is
// one self-contained file with no CSS import to resolve.
const LENIS_CSS = 'html.lenis,html.lenis body{height:auto}'
  + '.lenis:not(.lenis-autoToggle).lenis-stopped{overflow:clip}'
  + '.lenis [data-lenis-prevent],.lenis [data-lenis-prevent-wheel],.lenis [data-lenis-prevent-touch],'
  + '.lenis [data-lenis-prevent-vertical],.lenis [data-lenis-prevent-horizontal]{overscroll-behavior:contain}'
  + '.lenis.lenis-smooth iframe{pointer-events:none}'
  + '.lenis.lenis-autoToggle{transition-property:overflow;transition-duration:1ms;transition-behavior:allow-discrete}';

function routeMatches(route: string, pathname: string): boolean {
  const rs = route.split('/').filter(Boolean);
  const ps = pathname.split('/').filter(Boolean);
  for (let i = 0; i < rs.length; i++) {
    if (/^\\[\\.\\.\\..+\\]$/.test(rs[i])) return true;
    if (i >= ps.length) return false;
    if (/^\\[.+\\]$/.test(rs[i])) continue;
    if (rs[i] !== ps[i]) return false;
  }
  return rs.length === ps.length;
}

function resolve(map: any, pathname: string): any {
  const p = pathname || '/';
  if (map && map.pages && map.pages[p]) return map.pages[p];
  for (const route of Object.keys((map && map.pages) || {})) if (routeMatches(route, p)) return map.pages[route];
  return (map && map.__default) || null;
}

export function SmoothScroll() {
  const pathname = usePathname();
  React.useEffect(() => {
    if (typeof window === 'undefined') return;
    const cfg = resolve(SMOOTH_SCROLL, pathname || '/');
    if (!cfg || cfg.enabled === false) return;
    // Visitors who asked for less motion keep native scrolling.
    if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const horizontal = cfg.orientation === 'horizontal';
    const style = document.createElement('style');
    style.setAttribute('data-revyme-lenis', '');
    style.textContent = LENIS_CSS;
    document.head.appendChild(style);
    const lenis = new Lenis({
      duration: Math.max(0.1, Number(cfg.intensity ?? 12) / 10),
      smoothWheel: cfg.smoothWheel !== false,
      syncTouch: cfg.smoothTouch === true,
      orientation: horizontal ? 'horizontal' : 'vertical',
      gestureOrientation: horizontal ? 'both' : 'vertical',
      infinite: cfg.infinite === true,
      autoRaf: true,
      anchors: true,
      allowNestedScroll: true,
      stopInertiaOnNavigate: true,
    });
    (window as any).__revymeLenis = lenis;
    return () => {
      lenis.destroy();
      style.remove();
      if ((window as any).__revymeLenis === lenis) delete (window as any).__revymeLenis;
    };
  }, [pathname]);
  return null;
}
`;

/** Write the data module (when missing) and the controller (when missing or outdated). */
export function ensureSmoothScrollScaffold(): void {
  if (projectFS.readFile(SMOOTH_SCROLL_DATA_PATH) == null) {
    projectFS.writeFile(SMOOTH_SCROLL_DATA_PATH, serializeSmoothScroll({ pages: {} }));
  }
  const existing = projectFS.readFile(SMOOTH_SCROLL_CONTROLLER_PATH);
  if (existing == null || !existing.includes(SMOOTH_SCROLL_MARKER)) {
    projectFS.writeFile(SMOOTH_SCROLL_CONTROLLER_PATH, SMOOTH_SCROLL_CONTROLLER_SOURCE);
  }
  trace.action('smooth-scroll-gen:ensure-scaffold', {});
}

export { ensureSmoothScrollInLayout } from './smooth-scroll-layout';
