import { test, expect } from '@playwright/test';
import { EditorPage } from '../../canvas/drag/e2e/helpers/editor-page';

for (const mode of ['dark', 'light'] as const) {
  test(`${mode}: rounded shells, composite pills and panel insets survive navigation`, async ({ page }) => {
    await page.addInitScript(value => localStorage.setItem('revyme:prefs:themeMode', JSON.stringify(value)), mode);
    const editor = new EditorPage(page);
    await editor.gotoWithSeed('ABSOLUTE_IN_FRAME');
    const toolbar = page.locator('#bottom-toolbar-container').last();
    const radius = await toolbar.evaluate(el => ({ shell: getComputedStyle(el).borderTopLeftRadius, stroke: getComputedStyle(el, '::after').borderTopLeftRadius }));
    expect(parseFloat(radius.shell)).toBeGreaterThan(0);
    expect(radius.stroke).toBe(radius.shell);
    expect(await page.locator('[data-field-pages-tree]').evaluate(el => parseFloat(getComputedStyle(el).paddingTop))).toBe(12);
    expect(await page.locator('[data-document-layers] [data-layers-scroll]').evaluate(el => parseFloat(getComputedStyle(el).paddingTop))).toBe(12);
    const selectedTool = toolbar.locator('[data-toolbar-tool="select"]');
    const highlight = await toolbar.evaluate(el => { const button = el.querySelector('[data-toolbar-tool="select"]')!; const shell = el.getBoundingClientRect(); const inner = button.getBoundingClientRect(); return { radius: getComputedStyle(button).borderTopLeftRadius.split(' ').map(Number.parseFloat), x: inner.left - shell.left, y: inner.top - shell.top }; });
    expect(highlight.radius[0]).toBeCloseTo(parseFloat(radius.shell) - highlight.x, 2);
    expect(highlight.radius[1]).toBeCloseTo(parseFloat(radius.shell) - highlight.y, 2);
    await selectedTool.hover();
    await toolbar.screenshot({ path: `../screenshots/field-candidate-${mode}-toolbar-highlight.png` });
    const appearanceTrigger = page.locator('[data-editor-appearance]');
    await expect(appearanceTrigger.locator('[data-appearance-brush]')).toBeVisible();
    await appearanceTrigger.focus();
    await expect(appearanceTrigger).toBeFocused();
    await page.keyboard.press('Enter');
    const appearance = page.getByRole('dialog', { name: /^appearance$/i });
    await expect(appearance).toBeVisible();
    const appearanceBounds = await appearance.boundingBox();
    expect(appearanceBounds!.y).toBeGreaterThanOrEqual(12);
    expect(appearanceBounds!.y + appearanceBounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height - 12);
    await expect(appearance.getByRole('switch')).toBeFocused();
    await expect(appearance.getByRole('switch')).toHaveAttribute('aria-checked', String(mode === 'dark'));
    await appearance.locator('[data-appearance-swatch]').last().click();
    const chosenAccent = await appearance.locator('[aria-pressed="true"]').getAttribute('data-appearance-swatch');
    await expect(appearance.locator('[data-appearance-preview]')).toBeVisible();
    await page.screenshot({ path: `../screenshots/field-candidate-${mode}-appearance.png` });
    await page.keyboard.press('Escape');
    await expect(appearance).not.toBeVisible();
    await expect(appearanceTrigger).toBeFocused();
    await page.getByRole('button', { name: 'Open menu', exact: true }).click();
    await page.getByRole('menuitem', { name: /^appearance$/i }).hover();
    await expect(appearance).toBeVisible();
    await expect(appearance.locator(`[data-appearance-swatch="${chosenAccent}"]`)).toHaveAttribute('aria-pressed', 'true');
    await expect(appearance.getByRole('switch')).toHaveAttribute('aria-checked', String(mode === 'dark'));
    await appearance.getByRole('switch').click();
    await page.keyboard.press('Escape');
    await appearanceTrigger.click();
    await expect(appearance.getByRole('switch')).toHaveAttribute('aria-checked', String(mode !== 'dark'));
    await appearance.getByRole('switch').click();
    await page.keyboard.press('Escape');
    await editor.select(['abs-child'], 'desktop');
    const pill = page.locator('[data-figma-dimension="width"]').first();
    await expect(pill).toBeVisible();
    expect(await pill.evaluate(el => getComputedStyle(el).boxShadow)).not.toBe('none');
    expect(await pill.locator('input').evaluate(el => getComputedStyle(el).boxShadow)).toBe('none');
    await expect(pill.locator('input')).toBeEnabled();
    await pill.locator('input').click({ position: { x: 8, y: 12 } });
    await expect(pill.locator('input')).toBeFocused();
    expect(await pill.evaluate(el => getComputedStyle(el).outlineStyle)).toBe('solid');
    await pill.screenshot({ path: `../screenshots/field-candidate-${mode}-width-pill.png` });
    await page.keyboard.press('Escape');
    await editor.select(['root'], 'desktop');
    await page.locator('[data-tutorial="library-button"]').click();
    const libraryContent = page.locator('[data-editor-panel="left-primary"] [data-library-section] [data-field-section-label] + :not([data-tool-divider])').first();
    await expect(libraryContent).toBeVisible();
    expect(await libraryContent.evaluate(el => parseFloat(getComputedStyle(el).marginTop))).toBe(12);
    await page.locator('[data-tutorial="cms-button"]').click();
    const cmsContent = page.locator('[data-field-task-panel] > :not([data-field-section-label]):not([data-tool-divider])').first();
    await expect(cmsContent).toBeVisible();
    expect(await cmsContent.evaluate(el => parseFloat(getComputedStyle(el).paddingTop))).toBe(12);
    const segmented = page.locator('[data-inspector-icon-group]').first();
    await expect(segmented).toBeAttached();
    expect(await segmented.evaluate(el => getComputedStyle(el).boxShadow)).not.toBe('none');
    expect(await segmented.locator('button').first().evaluate(el => getComputedStyle(el).boxShadow)).toBe('none');
    await page.locator('[data-tutorial="branches-button"]').click();
    const rows = page.locator('[data-field-task-panel] > .overflow-y-auto');
    expect(await rows.evaluate(el => parseFloat(getComputedStyle(el).paddingTop))).toBe(12);
    await page.getByRole('button', { name: /^draw text \(t\) options$/i }).click();
    const popup = page.locator('[data-toolbar-dropdown]');
    const popupRadius = await popup.evaluate(el => ({ shell: getComputedStyle(el).borderTopLeftRadius, stroke: getComputedStyle(el, '::after').borderTopLeftRadius }));
    expect(parseFloat(popupRadius.shell)).toBeGreaterThan(0);
    expect(popupRadius.stroke).toBe(popupRadius.shell);
    const menuShadow = await popup.evaluate(el => getComputedStyle(el).boxShadow);
    expect(menuShadow).toContain(mode === 'light' ? '0.08' : '0.16');
    await expect.poll(() => popup.evaluate(el => getComputedStyle(el).opacity)).toBe('1');
    await page.screenshot({ path: `../screenshots/field-global-${mode}-menu.png` });
    await page.keyboard.press('Escape');
    await page.locator('[data-tutorial="media-button"]').click();
    const media = page.locator('[data-editor-panel="left-primary"]');
    await expect(media.getByRole('button', { name: 'Add media', exact: true })).toHaveCount(1);
    expect(await media.locator('[data-media-filter-tabs]').evaluate(el => parseFloat(getComputedStyle(el).paddingBottom))).toBeGreaterThanOrEqual(8);
    const titleGap = await media.locator('[data-media-filter-tabs]').evaluate(el => el.firstElementChild!.getBoundingClientRect().top - el.previousElementSibling!.getBoundingClientRect().bottom);
    expect(titleGap).toBe(12);
    const outerGap = await media.locator('[data-field-panel-section]').evaluate(el => el.getBoundingClientRect().top - document.querySelector('[data-workspace-left-header]')!.getBoundingClientRect().bottom);
    expect(outerGap).toBe(12);
    const filters = media.locator('[data-tool-segmented]');
    const filterGeometry = await filters.evaluate(el => ({ outer: parseFloat(getComputedStyle(el).borderTopLeftRadius), inset: parseFloat(getComputedStyle(el).paddingTop) + parseFloat(getComputedStyle(el).borderTopWidth), inner: parseFloat(getComputedStyle(el.querySelector('button')!).borderTopLeftRadius) }));
    expect(filterGeometry.inner).toBe(filterGeometry.outer - filterGeometry.inset);
    const depths = await page.evaluate(() => ({ section: getComputedStyle(document.querySelector('[data-field-panel-section]')!).boxShadow, panel: getComputedStyle(document.querySelector('[data-workspace-island="left"]')!).boxShadow }));
    const sectionAlpha = Number(depths.section.match(/rgba\([^)]*, ([\d.]+)\)/)![1]);
    expect(sectionAlpha).toBeCloseTo(mode === 'light' ? 0.105 : 0.14, 2);
    expect(depths.panel).toContain(mode === 'light' ? '0.12' : '0.24');
    for (const geometry of [{radius: 14, x: 5, y: 3}, {radius: 9999, x: 4, y: 4}]) {
      await filters.evaluate((el, value) => { const shell = el as HTMLElement; shell.style.setProperty('--field-selection-shell-radius', `${value.radius}px`); shell.style.setProperty('--field-selection-inset-x', `${value.x}px`); shell.style.setProperty('--field-selection-inset-y', `${value.y}px`); }, geometry);
      const actual = await filters.locator('button').first().evaluate(el => getComputedStyle(el).borderTopLeftRadius.split(' ').map(Number.parseFloat));
      expect(actual[0]).toBe(geometry.radius - geometry.x);
      expect(actual[1] ?? actual[0]).toBe(geometry.radius - geometry.y);
    }
    await filters.evaluate(el => (el as HTMLElement).removeAttribute('style'));
    await filters.getByRole('button', { name: 'Images', exact: true }).focus();
    await page.keyboard.press('ArrowRight');
    await expect(filters.getByRole('button', { name: 'Videos', exact: true })).toBeFocused();
    await page.keyboard.press('Enter');
    await expect(filters.getByRole('button', { name: 'Videos', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await filters.getByRole('button', { name: 'All', exact: true }).click();
    await page.screenshot({ path: `../screenshots/field-global-${mode}-media.png` });
    const layoutTrigger = page.locator('[data-workspace-mode-trigger]').first();
    expect(await layoutTrigger.evaluate(el => getComputedStyle(el).boxShadow)).toBe('none');
    await page.locator('[data-settings-gear]').first().screenshot({ path: `../screenshots/field-global-${mode}-gear.png` });
    await media.getByPlaceholder('Search media…').fill('preserved search');
    await media.locator('[data-media-gallery-entry]').click();
    const gallery = page.getByRole('dialog', { name: 'Gallery', exact: true });
    await expect(gallery).toBeVisible();
    await expect(gallery.locator('[data-gallery-glyph]').first()).toBeVisible();
    await gallery.getByRole('button', { name: 'Back to Media', exact: true }).click();
    await expect(gallery).not.toBeVisible();
    await expect(media.getByPlaceholder('Search media…')).toHaveValue('preserved search');
    await media.locator('[data-media-gallery-entry]').click();
    await page.keyboard.press('Escape');
    await expect(gallery).not.toBeVisible();
    await expect(media.getByPlaceholder('Search media…')).toHaveValue('preserved search');
    await media.getByPlaceholder('Search media…').fill('');
    await page.setViewportSize({ width: 1024, height: 768 });
    await expect(media.locator('[data-media-gallery-entry]')).toBeVisible();
    const bounds = await toolbar.boundingBox();
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(1024);
    await page.screenshot({ path: `../screenshots/field-candidate-${mode}-landscape.png` });
    const chooser = page.locator('[data-workspace-layout-control]:visible').first();
    await chooser.locator('[data-workspace-mode-trigger]').focus();
    await page.keyboard.press('Enter');
    await chooser.getByRole('button', { name: /^float layout:/i }).focus();
    await page.keyboard.press('Enter');
    const floatingMedia = page.locator('[data-floating-left-panel="media"]');
    await expect.poll(() => page.locator('[data-workspace-left-header]').evaluate(el => Math.round(el.getBoundingClientRect().top))).toBe(12);
    await page.locator('[data-tutorial="media-button"]').click();
    await expect(floatingMedia).toHaveAttribute('data-visible', 'true');
    await expect(floatingMedia).toBeVisible();
    const floatingShadow = await page.locator('[data-workspace-island="left"]').evaluate(el => getComputedStyle(el).boxShadow);
    expect(floatingShadow).toContain('0.24');
    await expect.poll(() => floatingMedia.evaluate(el => getComputedStyle(el).opacity)).toBe('1');
    await page.screenshot({ path: `../screenshots/field-global-${mode}-floating.png` });
    await chooser.locator('[data-workspace-mode-trigger]').focus();
    await page.keyboard.press('Enter');
    await chooser.getByRole('button', { name: /^full layout:/i }).focus();
    await page.keyboard.press('Enter');
    await expect(page.locator('[data-workspace-left-header]')).toHaveAttribute('data-title-presentation', 'embedded');
    await chooser.locator('[data-workspace-mode-trigger]').focus();
    await page.keyboard.press('Enter');
    await expect(chooser).toHaveAttribute('data-expanded', 'true');
    await page.keyboard.press('Escape');
    await expect(chooser).toHaveAttribute('data-expanded', 'false');
    await expect(chooser.locator('[data-workspace-mode-trigger]')).toBeFocused();
    for (const strength of [1, 0.5]) {
      await page.evaluate(value => document.documentElement.style.setProperty('--field-bevel-strength', String(value)), strength);
      await page.screenshot({ path: `../screenshots/field-bevel-${mode}-${strength === 1 ? 'before' : 'after'}.png` });
    }
    const alphas = await toolbar.evaluate(el => ({ stroke: getComputedStyle(el, '::after').borderTopColor, opacity: getComputedStyle(el).opacity }));
    expect(alphas.stroke).toBe('rgba(128, 128, 128, 0.15)');
    expect(alphas.opacity).toBe('1');
  });
}

test('one Media upload action remains usable in empty and populated inventory', async ({ page }) => {
  const editor = new EditorPage(page);
  await editor.gotoWithSeed('ABSOLUTE_IN_FRAME');
  await page.locator('[data-tutorial="media-button"]').click();
  const media = page.locator('[data-editor-panel="left-primary"]');
  const chooser = page.waitForEvent('filechooser');
  await media.getByRole('button', { name: 'Add media', exact: true }).click();
  await (await chooser).setFiles({ name: 'regression.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jOjQAAAAASUVORK5CYII=', 'base64') });
  await expect(media.locator('[data-media-grid] img').first()).toBeVisible();
  await expect(media.getByRole('button', { name: 'Add media', exact: true })).toHaveCount(1);
  await media.locator('[data-media-gallery-entry]').click();
  await page.getByRole('button', { name: 'Back to Media', exact: true }).click();
  await expect(media.locator('[data-media-grid] img').first()).toBeVisible();
});
